config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :todolists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    attachment :image
    
    validates :title, presence: true
    validates :body, presence: true
    validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
end

app/controllers/todolist_controller.rb
class TodolistController < ApplicationController
  def new
    @list = List.new
  end
  def create
    list = List.new(list_params)
    list.save
    redirect_to :top
  end 
  
  private
  def list_params
    params.require(:list).permit(:title,:body)
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def index
    @lists = List.all
  end
  
  def show
    @list = List.find(params[:id])
  end 
  
  def new
    @list = List.new
  end
  
  def edit
    @list = List.find(params[:id])
  end
  
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to todolist_path(@list.id)
    else
      render :new
    end
  end 
  
  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to todolists_path
  end
  
  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to todolist_path(@list.id)
    else
      render :edit
    end
  end
  
  private
  def list_params
    params.require(:list).permit(:title,:body,:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/todolist_helper.rb
module TodolistHelper
end

app/views/homes/top.html.erb
<h1>トップページ</h1>
<%= link_to "トップページ", todolists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlacticeRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolist/new.html.erb
<%= form_with model:@list,url:'/todolist',local:true do |f| %>
<div>
    <label>タイトル</label>
    <%= f.text_field:title %>
</div>
<div>
    <label>本文</label>
    <%= f.text_area:body %>
</div>
<div>
    <%= f.submit "投稿" %>
</div>
<% end %>

app/views/todolists/edit.html.erb
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <% @list.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<h1>編集</h1>
<%= form_with model:@list,url: todolist_path(@list.id),local:true do |f| %>
<div>
    <lable>画像</lable>
    <%= f.attachment_field:image %>
</div>
<div>
    <label>タイトル</label>
    <%= f.text_field:title %>
</div>
<div>
    <label>本文</label>
    <%= f.text_area:body %>
</div>
<div>
    <%= f.submit "更新" %>
</div>
<% end %>

app/views/todolists/index.html.erb
<%= link_to "投稿", new_todolist_path %>
<h1>一覧</h1>
<% @lists.each do |list| %>
<table>
    <tr>
        <th>画像</th>
        <%= attachment_image_tag list,:image,size: '100x100' %>
    </tr>
    <tr>
        <th>タイトル</th>
        <td><%= link_to list.title,todolist_path(list.id) %></td>
    </tr>
    <tr>
        <th>本文</th>
        <td><%= list.body %></td>
    </tr>
</table>
<% end %>

app/views/todolists/new.html.erb
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <% @list.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model:@list,url: todolists_path,local:true do |f| %>
<div>
    <label>画像</label>
    <%= f.attachment_field:image %>
</div>
<div>
    <label>タイトル</label>
    <%= f.text_field:title %>
</div>
<div>
    <label>本文</label>
    <%= f.text_area:body %>
</div>
<div>
    <%= f.submit "投稿" %>
</div>
<% end %>

app/views/todolists/show.html.erb
<h1>詳細</h1>
<table>
    <tr>
        <th>画像</th>
        <td><%= attachment_image_tag @list,:image,size: '100x100' %></td>
    </tr>
    <tr>
        <th>タイトル</th>
        <td><%= @list.title %></td>
    </tr>
    <tr>
        <th>本文</th>
        <td><%= @list.body %></td>
    </tr>
</table>
<%= link_to '編集', edit_todolist_path(@list.id) %>
<%= link_to "削除", todolist_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>